# Generated by Django 5.0.14 on 2026-04-29 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agentjob_mail_alias_quota_choices'),
        ('hosting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingaccount',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosting_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostingaccount',
            name='reseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reseller_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='hostingaccount',
            index=models.Index(fields=['owner', 'status'], name='hosting_hos_owner_i_07962e_idx'),
        ),
        migrations.AddIndex(
            model_name='hostingaccount',
            index=models.Index(fields=['reseller', 'status'], name='hosting_hos_reselle_e32a71_idx'),
        ),
    ]
