# Generated by Django 5.0.14 on 2026-04-30 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_hostingaccount_owner_hostingaccount_reseller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingDNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='@', max_length=255)),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('TXT', 'TXT')], max_length=10)),
                ('content', models.TextField()),
                ('ttl', models.PositiveIntegerField(default=300)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='hosting.hostingdomain')),
            ],
            options={
                'ordering': ['domain__domain', 'name', 'record_type'],
                'indexes': [models.Index(fields=['domain', 'record_type'], name='hosting_hos_domain__08ccf4_idx')],
                'unique_together': {('domain', 'name', 'record_type')},
            },
        ),
    ]
