# Generated by Django 5.0.14 on 2026-04-30 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_agentjob_job_type'),
        ('hosting', '0003_hostingdnsrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('wordpress', 'WordPress')], default='wordpress', max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('install_path', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('installing', 'Installing'), ('active', 'Active'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('version', models.CharField(blank=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hosting.hostingaccount')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='hosting.hostingdomain')),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'app_type', 'status'], name='hosting_hos_account_26fc8d_idx'), models.Index(fields=['domain', 'app_type'], name='hosting_hos_domain__1c827c_idx')],
                'unique_together': {('domain', 'app_type')},
            },
        ),
    ]
