# Generated by Django 5.0.14 on 2026-05-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0004_hostingapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingapplication',
            name='app_type',
            field=models.CharField(choices=[('wordpress', 'WordPress'), ('python', 'Python'), ('nodejs', 'Node.js')], default='wordpress', max_length=30),
        ),
    ]
