# Generated by Django 5.0.14 on 2026-05-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0005_alter_hostingapplication_app_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('installing', 'Installing'), ('active', 'Active'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
