# Generated by Django 5.0.14 on 2026-05-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0007_alter_hostingapplication_app_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingapplication',
            name='app_type',
            field=models.CharField(choices=[('wordpress', 'WordPress'), ('python', 'Python'), ('django', 'Django'), ('nodejs', 'Node.js'), ('laravel', 'Laravel')], default='wordpress', max_length=30),
        ),
    ]
