# Generated by Django 5.0.14 on 2026-05-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0008_alter_hostingapplication_app_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingaccount',
            name='last_usage',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hostingaccount',
            name='last_usage_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
