# Generated by Django 5.0.14 on 2026-05-09 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0009_hostingaccount_last_usage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('account.created', 'Account created'), ('account.updated', 'Account updated'), ('account.password_changed', 'Account password changed'), ('account.synced', 'Account synced'), ('account.retry_failed', 'Account retry failed'), ('provisioning.step_retried', 'Provisioning step retried')], max_length=80)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='hosting.hostingaccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='hosting_aud_action_6b15e4_idx'), models.Index(fields=['account', 'created_at'], name='hosting_aud_account_983a61_idx'), models.Index(fields=['user', 'created_at'], name='hosting_aud_user_id_4506ad_idx')],
            },
        ),
    ]
