# Generated by Django 5.0.14 on 2026-05-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0010_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingdomain',
            name='dkim_selector',
            field=models.CharField(default='ehpanel', max_length=64),
        ),
        migrations.AddField(
            model_name='hostingdomain',
            name='dkim_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='hostingdomain',
            name='dkim_txt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hostingdnsrecord',
            name='record_type',
            field=models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('NS', 'NS'), ('SRV', 'SRV'), ('TXT', 'TXT')], max_length=10),
        ),
        migrations.CreateModel(
            name='DNSTemplateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('NS', 'NS'), ('SRV', 'SRV'), ('TXT', 'TXT')], max_length=10)),
                ('content', models.TextField()),
                ('ttl', models.PositiveIntegerField(default=300)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name', 'record_type'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='hosting_dns_is_acti_1f81e6_idx')],
                'unique_together': {('name', 'record_type')},
            },
        ),
    ]
