# Generated by Django 5.0.14 on 2026-05-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0012_seed_dns_template_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingdomain',
            name='ssl_cert_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hostingdomain',
            name='ssl_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hostingdomain',
            name='ssl_error_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='hostingdomain',
            name='ssl_error_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hostingdomain',
            name='ssl_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostingdomain',
            name='ssl_issuer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='hostingdomain',
            name='ssl_privkey_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
