# Generated by Django 5.0.14 on 2026-05-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0013_hostingdomain_ssl_cert_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingmailbox',
            name='last_test_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostingmailbox',
            name='last_test_recipient',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hostingmailbox',
            name='last_test_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hostingmailbox',
            name='last_test_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='hostingmailbox',
            name='last_usage_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostingmailbox',
            name='usage_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='hostingmailbox',
            name='used_mb',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
