# Generated by Django 5.0.14 on 2026-05-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0014_hostingmailbox_last_test_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingdatabase',
            name='last_size_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostingdatabase',
            name='size_mb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostingdatabase',
            name='size_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
