# Generated by Django 5.0.14 on 2026-05-09 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0021_alter_agentjob_job_type'),
        ('hosting', '0015_hostingdatabase_last_size_at_hostingdatabase_size_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingplan',
            name='allowed_php_versions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hostingplan',
            name='allowed_web_engines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hostingplan',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=80, unique=True)),
                ('default_public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dns_defaults', models.JSONField(blank=True, default=dict)),
                ('ssl_defaults', models.JSONField(blank=True, default=dict)),
                ('mail_defaults', models.JSONField(blank=True, default=dict)),
                ('paths', models.JSONField(blank=True, default=dict)),
                ('policies', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.node')),
            ],
            options={
                'verbose_name': 'Global configuration',
                'verbose_name_plural': 'Global configuration',
            },
        ),
    ]
