# Generated by Django 5.0.14 on 2026-05-12 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0022_alter_agentjob_job_type'),
        ('hosting', '0019_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingFtpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(max_length=64, unique=True)),
                ('root', models.CharField(default='public_html', max_length=255)),
                ('protocol', models.CharField(default='FTPES / explicit TLS', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ftp_users', to='hosting.hostingaccount')),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentjob')),
            ],
            options={
                'ordering': ['account__primary_domain', 'username'],
                'indexes': [models.Index(fields=['account', 'status'], name='hosting_hos_account_3ecdb2_idx')],
            },
        ),
    ]
