# Generated by Django 5.0.14 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosting", "0020_hostingftpuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostingftpuser",
            name="quota_mb",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
