# Generated by Django 5.0.14 on 2026-05-12 21:49

import django.db.models.deletion
from django.db import migrations, models


def backfill_database_users(apps, schema_editor):
    HostingDatabase = apps.get_model('hosting', 'HostingDatabase')
    HostingDatabaseUser = apps.get_model('hosting', 'HostingDatabaseUser')
    HostingDatabaseGrant = apps.get_model('hosting', 'HostingDatabaseGrant')
    for database in HostingDatabase.objects.exclude(username=''):
        user, _ = HostingDatabaseUser.objects.get_or_create(
            account_id=database.account_id,
            engine=database.engine,
            username=database.username,
            defaults={'access': 'admin', 'hosts': ['localhost'], 'status': database.status},
        )
        HostingDatabaseGrant.objects.get_or_create(
            database_id=database.id,
            user_id=user.id,
            defaults={'access': user.access, 'privileges': ['ALL']},
        )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0026_alter_agentjob_job_type'),
        ('hosting', '0021_hostingftpuser_quota_mb'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingDatabaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('mariadb', 'MariaDB'), ('postgresql', 'PostgreSQL')], default='mariadb', max_length=20)),
                ('username', models.CharField(max_length=64)),
                ('access', models.CharField(choices=[('read_only', 'Solo lectura'), ('read_write', 'Lectura y escritura'), ('admin', 'Admin')], default='read_write', max_length=20)),
                ('hosts', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_users', to='hosting.hostingaccount')),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentjob')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='HostingDatabaseGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(choices=[('read_only', 'Solo lectura'), ('read_write', 'Lectura y escritura'), ('admin', 'Admin')], default='read_write', max_length=20)),
                ('privileges', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='hosting.hostingdatabase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='hosting.hostingdatabaseuser')),
            ],
            options={
                'ordering': ['database__name', 'user__username'],
            },
        ),
        migrations.AddConstraint(
            model_name='hostingdatabaseuser',
            constraint=models.UniqueConstraint(fields=('account', 'engine', 'username'), name='unique_hosting_database_user_per_account_engine'),
        ),
        migrations.AddConstraint(
            model_name='hostingdatabasegrant',
            constraint=models.UniqueConstraint(fields=('database', 'user'), name='unique_hosting_database_grant'),
        ),
        migrations.RunPython(backfill_database_users, noop_reverse),
    ]
