# Generated by Django 5.0.14 on 2026-05-13 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0023_hostingdatabasecredential_hostingdatabasessotoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingmailbox',
            name='antispam_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hostingmailbox',
            name='antispam_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hostingmailbox',
            name='autoresponder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostingmailbox',
            name='autoresponder_encoding',
            field=models.CharField(default='UTF-8', max_length=40),
        ),
        migrations.AddField(
            model_name='hostingmailbox',
            name='autoresponder_format',
            field=models.CharField(default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='hostingmailbox',
            name='autoresponder_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hostingmailbox',
            name='autoresponder_redirect',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hostingmailbox',
            name='autoresponder_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostingmailbox',
            name='autoresponder_subject',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='hostingmailbox',
            name='autoresponder_unique_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hostingmailbox',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hostingmailbox',
            name='outgoing_limit',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.CreateModel(
            name='HostingMailboxCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_password', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailbox', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='hosting.hostingmailbox')),
            ],
        ),
        migrations.CreateModel(
            name='HostingMailboxSsoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_tokens', to='hosting.hostingmailbox')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
