# Generated by Django 5.0.14 on 2026-05-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0025_seed_mail_autoconfig_records'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dnstemplaterecord',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='hostingdnsrecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dnstemplaterecord',
            name='record_type',
            field=models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('NS', 'NS'), ('SRV', 'SRV'), ('TXT', 'TXT'), ('CAA', 'CAA')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hostingdnsrecord',
            name='record_type',
            field=models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('NS', 'NS'), ('SRV', 'SRV'), ('TXT', 'TXT'), ('CAA', 'CAA')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='dnstemplaterecord',
            unique_together={('name', 'record_type', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='hostingdnsrecord',
            unique_together={('domain', 'name', 'record_type', 'content')},
        ),
    ]
