# Generated by Django 5.0.14 on 2026-05-13 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0030_alter_agentjob_job_type'),
        ('hosting', '0029_hostingprotecteddirectory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingWafConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('disabled', 'Disabled'), ('monitor', 'Monitor'), ('block', 'Block')], default='monitor', max_length=20)),
                ('owasp_crs', models.BooleanField(default=True)),
                ('wordpress_rules', models.BooleanField(default=True)),
                ('block_xmlrpc', models.BooleanField(default=True)),
                ('rate_limit_login', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waf_configuration', to='hosting.hostingdomain')),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentjob')),
            ],
            options={
                'ordering': ['domain__domain'],
            },
        ),
        migrations.CreateModel(
            name='HostingIPBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=255)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('disabled', 'Disabled'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_blocks', to='hosting.hostingdomain')),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentjob')),
            ],
            options={
                'ordering': ['domain__domain', '-created_at'],
                'indexes': [models.Index(fields=['domain', 'status'], name='hosting_hos_domain__0c1a57_idx')],
                'unique_together': {('domain', 'target')},
            },
        ),
    ]
