# Generated by Django 5.0.14 on 2026-05-13 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0030_alter_agentjob_job_type'),
        ('hosting', '0030_hostingwafconfiguration_hostingipblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingSecurityScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='public_html', max_length=1024)),
                ('scan_type', models.CharField(choices=[('full', 'Full'), ('quick', 'Quick'), ('manual', 'Manual')], default='quick', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('clean', 'Clean'), ('threat', 'Threat'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('files_scanned', models.PositiveIntegerField(default=0)),
                ('infected_files', models.PositiveIntegerField(default=0)),
                ('data_scanned', models.CharField(blank=True, max_length=80)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('output', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_detail', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_scans', to='hosting.hostingaccount')),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'status'], name='hosting_hos_account_eb36c8_idx'), models.Index(fields=['scan_type', 'created_at'], name='hosting_hos_scan_ty_60fb54_idx')],
            },
        ),
    ]
