# Generated by Django 5.0.14 on 2026-05-13 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0032_apps_detection_catalog_backups'),
        ('hosting', '0031_hostingsecurityscan'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingApplicationBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('archive_path', models.CharField(blank=True, max_length=500)),
                ('filename', models.CharField(blank=True, max_length=180)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='hosting.hostingapplication')),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app', 'status'], name='hosting_hos_app_id_d796e7_idx')],
            },
        ),
    ]
