# Generated by Django 5.0.14 on 2026-05-14 09:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0032_apps_detection_catalog_backups'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingMonitorCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('http', 'HTTP'), ('dns', 'DNS'), ('ssl', 'SSL'), ('smtp', 'SMTP'), ('webmail', 'Webmail'), ('service', 'Service')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('target', models.CharField(max_length=255)),
                ('interval_seconds', models.PositiveIntegerField(default=60)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('failed', 'Failed'), ('paused', 'Paused'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('response_ms', models.PositiveIntegerField(default=0)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_checks', to='hosting.hostingaccount')),
            ],
            options={
                'ordering': ['account__primary_domain', 'check_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HostingMonitorIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('service', models.CharField(blank=True, max_length=80)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_incidents', to='hosting.hostingaccount')),
                ('monitor_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='hosting.hostingmonitorcheck')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HostingMonitorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('uptime_pct', models.FloatField(default=0)),
                ('response_ms', models.PositiveIntegerField(default=0)),
                ('incidents_open', models.PositiveIntegerField(default=0)),
                ('services', models.JSONField(blank=True, default=list)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('logs', models.JSONField(blank=True, default=dict)),
                ('sla', models.JSONField(blank=True, default=dict)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_snapshots', to='hosting.hostingaccount')),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='HostingMonitorAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('webhook', 'Webhook'), ('panel', 'Panel')], default='email', max_length=20)),
                ('event', models.CharField(max_length=80)),
                ('threshold', models.CharField(blank=True, max_length=120)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_alert_rules', to='hosting.hostingaccount')),
            ],
            options={
                'ordering': ['account__primary_domain', 'channel', 'event'],
                'indexes': [models.Index(fields=['account', 'enabled'], name='hosting_hos_account_3362fb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='hostingmonitorcheck',
            index=models.Index(fields=['account', 'status'], name='hosting_hos_account_657703_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hostingmonitorcheck',
            unique_together={('account', 'check_type', 'target')},
        ),
        migrations.AddIndex(
            model_name='hostingmonitorincident',
            index=models.Index(fields=['account', 'status'], name='hosting_hos_account_da6096_idx'),
        ),
        migrations.AddIndex(
            model_name='hostingmonitorincident',
            index=models.Index(fields=['severity', 'started_at'], name='hosting_hos_severit_afa73d_idx'),
        ),
        migrations.AddIndex(
            model_name='hostingmonitorsnapshot',
            index=models.Index(fields=['account', 'collected_at'], name='hosting_hos_account_d9a748_idx'),
        ),
    ]
