# Generated by Django 5.0.14 on 2026-05-14 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0040_alter_agentjob_job_type'),
        ('hosting', '0034_supportticket_supportticketmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingAdvancedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('git_repo', 'Git repository'), ('ssh_key', 'SSH key'), ('cron', 'Cron job'), ('variable', 'Environment variable'), ('redirect', 'Redirect'), ('header', 'Header'), ('webhook', 'Webhook'), ('vhost_manual', 'Manual vhost')], max_length=30)),
                ('name', models.CharField(max_length=160)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('pending', 'Pending'), ('failed', 'Failed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_items', to='hosting.hostingaccount')),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentjob')),
            ],
            options={
                'ordering': ['kind', 'name'],
                'indexes': [models.Index(fields=['account', 'kind'], name='hosting_hos_account_f71574_idx'), models.Index(fields=['account', 'status'], name='hosting_hos_account_6015e9_idx')],
            },
        ),
    ]
