# Generated by Django 5.0.14 on 2026-05-15 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_reseller_profiles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    User = apps.get_model(settings.AUTH_USER_MODEL.split(".")[0], settings.AUTH_USER_MODEL.split(".")[1])
    HostingResellerProfile = apps.get_model("hosting", "HostingResellerProfile")
    reseller_group = Group.objects.filter(name__iexact="reseller").first()
    if not reseller_group:
        return
    for user in User.objects.filter(groups=reseller_group):
        HostingResellerProfile.objects.get_or_create(
            user=user,
            defaults={
                "company_name": user.username,
                "status": "active" if user.is_active else "suspended",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0040_alter_agentjob_job_type'),
        ('hosting', '0035_hostingadvanceditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('account.created', 'Account created'), ('account.updated', 'Account updated'), ('account.password_changed', 'Account password changed'), ('account.synced', 'Account synced'), ('account.retry_failed', 'Account retry failed'), ('provisioning.step_retried', 'Provisioning step retried'), ('user.created', 'User created'), ('user.updated', 'User updated'), ('user.impersonated', 'User impersonated')], max_length=80),
        ),
        migrations.CreateModel(
            name='HostingResellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=160)),
                ('panel_domain', models.CharField(blank=True, max_length=255)),
                ('disk_mb', models.PositiveIntegerField(default=0)),
                ('bandwidth_mb', models.PositiveIntegerField(default=0)),
                ('max_accounts', models.PositiveIntegerField(default=0)),
                ('max_mailboxes', models.PositiveIntegerField(default=0)),
                ('max_databases', models.PositiveIntegerField(default=0)),
                ('max_domains', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hosting.hostingplan')),
                ('primary_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.node')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_reseller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name', 'user__username'],
                'indexes': [models.Index(fields=['status'], name='hosting_hos_status_fd373e_idx'), models.Index(fields=['primary_node'], name='hosting_hos_primary_ba9b8a_idx')],
            },
        ),
        migrations.RunPython(backfill_reseller_profiles, migrations.RunPython.noop),
    ]
