# Generated by Django 5.0.14 on 2026-05-15 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0041_alter_agentjob_job_type'),
        ('hosting', '0036_alter_auditlog_action_hostingresellerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('discover_only', 'Discover only'), ('select_and_migrate', 'Select and migrate'), ('auto_migrate_all', 'Auto migrate all')], default='select_and_migrate', max_length=40)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('migration_type', models.CharField(default='full', max_length=40)),
                ('concurrency', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('discovering', 'Discovering'), ('analyzed', 'Analyzed'), ('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='draft', max_length=30)),
                ('current_step', models.CharField(blank=True, max_length=160)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('total_accounts', models.PositiveIntegerField(default=0)),
                ('completed_accounts', models.PositiveIntegerField(default=0)),
                ('failed_accounts', models.PositiveIntegerField(default=0)),
                ('selected_accounts', models.JSONField(blank=True, default=list)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='migration_runs', to='agents.node')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_username', models.CharField(blank=True, max_length=120)),
                ('primary_domain', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('selected', 'Selected'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='detected', max_length=30)),
                ('current_step', models.CharField(blank=True, max_length=160)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('files_mb', models.PositiveIntegerField(default=0)),
                ('databases_count', models.PositiveIntegerField(default=0)),
                ('mailboxes_count', models.PositiveIntegerField(default=0)),
                ('subdomains_count', models.PositiveIntegerField(default=0)),
                ('detected', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_detail', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hosting.hostingaccount')),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentjob')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='hosting.migrationrun')),
            ],
            options={
                'ordering': ['primary_domain'],
            },
        ),
        migrations.CreateModel(
            name='MigrationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('cpanel', 'cPanel / WHM'), ('plesk', 'Plesk'), ('directadmin', 'DirectAdmin'), ('backup_url', 'Backup URL'), ('ehpanel', 'EHPanel Web')], max_length=30)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=22)),
                ('username', models.CharField(max_length=120)),
                ('auth_method', models.CharField(choices=[('password', 'SSH password'), ('ssh_key', 'SSH key'), ('api_token', 'API token')], default='password', max_length=30)),
                ('encrypted_secret', models.TextField(blank=True)),
                ('status', models.CharField(default='ready', max_length=30)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='migrationrun',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='hosting.migrationsource'),
        ),
        migrations.CreateModel(
            name='MigrationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=30)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='hosting.migrationaccount')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentjob')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='hosting.migrationrun')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='info', max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hosting.migrationaccount')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hosting.migrationrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['run', 'created_at'], name='hosting_mig_run_id_ce25ff_idx'), models.Index(fields=['account', 'created_at'], name='hosting_mig_account_cd10a5_idx'), models.Index(fields=['level'], name='hosting_mig_level_75b6c3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='migrationaccount',
            index=models.Index(fields=['run', 'status'], name='hosting_mig_run_id_4ff986_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationaccount',
            index=models.Index(fields=['primary_domain'], name='hosting_mig_primary_7ed123_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='migrationaccount',
            unique_together={('run', 'primary_domain')},
        ),
        migrations.AddIndex(
            model_name='migrationsource',
            index=models.Index(fields=['provider', 'host'], name='hosting_mig_provide_b3be2b_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationsource',
            index=models.Index(fields=['status'], name='hosting_mig_status_fdd595_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationrun',
            index=models.Index(fields=['status', 'created_at'], name='hosting_mig_status_6ee086_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationrun',
            index=models.Index(fields=['destination_node', 'status'], name='hosting_mig_destina_b7434f_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationstep',
            index=models.Index(fields=['run', 'status'], name='hosting_mig_run_id_fb5d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationstep',
            index=models.Index(fields=['account', 'status'], name='hosting_mig_account_caabc5_idx'),
        ),
    ]
