# Generated by Django 5.0.14 on 2026-05-15 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0042_alter_agentjob_job_type'),
        ('hosting', '0037_migrationrun_migrationaccount_migrationsource_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingAccountExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('export_type', models.CharField(default='full', max_length=40)),
                ('include_files', models.BooleanField(default=True)),
                ('include_databases', models.BooleanField(default=True)),
                ('include_mail', models.BooleanField(default=True)),
                ('include_subdomains', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('archive_path', models.CharField(blank=True, max_length=500)),
                ('filename', models.CharField(blank=True, max_length=180)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='hosting.hostingaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'status'], name='hosting_hos_account_b7d5bf_idx'), models.Index(fields=['status', 'created_at'], name='hosting_hos_status_82ff2c_idx')],
            },
        ),
    ]
