# Generated by Django 5.0.14 on 2026-05-15 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0038_hostingaccountexport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisioningTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('category', models.CharField(choices=[('hosting', 'Hosting account'), ('reseller', 'Reseller'), ('migration', 'Migration'), ('import', 'Import'), ('application', 'Application')], default='hosting', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('resources', models.JSONField(blank=True, default=dict)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('automation', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hosting.hostingplan')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='hosting_pro_categor_ac02d1_idx'), models.Index(fields=['slug'], name='hosting_pro_slug_81248a_idx')],
            },
        ),
    ]
