# Generated by Django 5.0.14 on 2026-05-15 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0042_alter_agentjob_job_type'),
        ('hosting', '0039_provisioningtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNameserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('role', models.CharField(default='Primario', max_length=60)),
                ('zone', models.CharField(default='ehclouding.com', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('review', 'Review'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_nameservers', to='agents.node')),
            ],
            options={
                'ordering': ['sequence', 'hostname'],
                'indexes': [models.Index(fields=['node', 'status'], name='hosting_glo_node_id_1915fe_idx'), models.Index(fields=['sequence'], name='hosting_glo_sequenc_a089b8_idx'), models.Index(fields=['zone'], name='hosting_glo_zone_8ff9e4_idx')],
            },
        ),
    ]
