# Generated by Django 5.0.14 on 2026-05-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0040_globalnameserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingipblock',
            name='source',
            field=models.CharField(choices=[('admin', 'Administrator'), ('waf_firewall', 'WAF / Firewall'), ('modsecurity', 'ModSecurity'), ('antispam', 'Anti-spam'), ('agent', 'Node agent')], default='waf_firewall', max_length=30),
        ),
    ]
