# Generated by Django 5.0.14 on 2026-05-16 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0042_alter_agentjob_job_type'),
        ('hosting', '0041_hostingipblock_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupStorageDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('storage_type', models.CharField(choices=[('local', 'Local'), ('s3', 'S3 compatible'), ('ftp', 'FTP externo'), ('ehpanel_drive', 'EHPanel Drive')], default='local', max_length=30)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('bucket', models.CharField(blank=True, max_length=160)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('username', models.CharField(blank=True, max_length=160)),
                ('secret', models.TextField(blank=True)),
                ('capacity_gb', models.PositiveIntegerField(default=0)),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('testing', 'Testing'), ('failed', 'Failed')], default='active', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['storage_type', 'status'], name='hosting_bac_storage_c76620_idx')],
            },
        ),
        migrations.CreateModel(
            name='BackupRestoreRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('restore_type', models.CharField(default='full', max_length=40)),
                ('include_files', models.BooleanField(default=True)),
                ('include_databases', models.BooleanField(default=True)),
                ('include_mail', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounts', models.ManyToManyField(blank=True, related_name='backup_restores', to='hosting.hostingaccount')),
                ('backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_runs', to='hosting.hostingaccountexport')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_restores', to='agents.node')),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentjob')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_restores', to='hosting.hostingresellerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='hosting_bac_status_f06f96_idx')],
            },
        ),
        migrations.CreateModel(
            name='BackupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('policy_type', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental'), ('partial', 'Partial'), ('realtime', 'Realtime')], default='incremental', max_length=30)),
                ('frequency', models.CharField(default='daily_02', max_length=120)),
                ('include_files', models.BooleanField(default=True)),
                ('include_databases', models.BooleanField(default=True)),
                ('include_mail', models.BooleanField(default=True)),
                ('include_config', models.BooleanField(default=True)),
                ('full_account', models.BooleanField(default=True)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('retention_copies', models.PositiveIntegerField(default=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='hosting.backupstoragedestination')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['policy_type', 'status'], name='hosting_bac_policy__145869_idx')],
            },
        ),
    ]
