# Generated by Django 5.0.14 on 2026-05-16 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0042_backupstoragedestination_backuprestorerun_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(blank=True)),
                ('audience', models.CharField(choices=[('all', 'Todos'), ('clients', 'Clientes'), ('resellers', 'Revendedores')], default='all', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('scheduled', 'Programado'), ('archived', 'Archivado')], default='draft', max_length=20)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_at', '-created_at'],
                'indexes': [models.Index(fields=['audience', 'status'], name='hosting_glo_audienc_565701_idx'), models.Index(fields=['publish_at', 'expires_at'], name='hosting_glo_publish_559bd5_idx')],
            },
        ),
    ]
