# Generated by Django 5.0.14 on 2026-05-16 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0043_globalannouncement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device', models.CharField(blank=True, max_length=180)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('role', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('closed', 'Cerrada'), ('expired', 'Expirada')], default='active', max_length=20)),
                ('refresh_jti', models.CharField(blank=True, db_index=True, max_length=80)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='hosting_acc_user_id_3d297f_idx'), models.Index(fields=['ip_address', 'status'], name='hosting_acc_ip_addr_b3ca18_idx')],
            },
        ),
    ]
