# Generated by Django 5.0.14 on 2026-05-16 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0048_default_integrations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('owner', models.CharField(default='Sistema', max_length=140)),
                ('route', models.CharField(default='/api/', max_length=255)),
                ('key_prefix', models.CharField(db_index=True, max_length=32)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('revoked', 'Revoked'), ('draft', 'Draft')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'owner'], name='hosting_api_status_3a676e_idx'), models.Index(fields=['created_at'], name='hosting_api_created_aae26b_idx')],
            },
        ),
    ]
