# Generated by Django 5.0.14 on 2026-05-16 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0049_apikeycredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingresellerprofile',
            name='brand_accent_color',
            field=models.CharField(blank=True, default='#0891b2', max_length=20),
        ),
        migrations.AddField(
            model_name='hostingresellerprofile',
            name='brand_primary_color',
            field=models.CharField(blank=True, default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='hostingresellerprofile',
            name='ip_allowlist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hostingresellerprofile',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='ResellerTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin_reseller', 'Administrador reseller'), ('support', 'Soporte'), ('commercial', 'Comercial')], default='support', max_length=30)),
                ('can_view_accounts', models.BooleanField(default=True)),
                ('can_manage_support', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='hosting.hostingresellerprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_team_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'indexes': [models.Index(fields=['reseller', 'status'], name='hosting_res_reselle_dc3ba8_idx')],
            },
        ),
    ]
