# Generated by Django 5.0.14 on 2026-05-19 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0043_node_agent_secret'),
        ('hosting', '0050_hostingresellerprofile_brand_accent_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingaccount',
            name='billing_client_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='hostingaccount',
            name='billing_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hostingaccount',
            name='billing_service_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='hostingaccount',
            name='billing_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='hostingaccount',
            name='billing_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
