# Generated by Django 5.0.14 on 2026-04-26 04:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('create_account', 'Create account'), ('delete_account', 'Delete account'), ('suspend_account', 'Suspend account'), ('unsuspend_account', 'Unsuspend account'), ('create_domain', 'Create domain'), ('delete_domain', 'Delete domain'), ('create_php_pool', 'Create PHP-FPM pool'), ('create_database', 'Create database'), ('create_dns_zone', 'Create DNS zone'), ('issue_ssl', 'Issue SSL certificate'), ('service_action', 'Service action')], max_length=80)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='queued', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_detail', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, max_length=80)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='agents.node')),
            ],
            options={
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['node', 'status'], name='agents_agen_node_id_892d19_idx'), models.Index(fields=['job_type', 'status'], name='agents_agen_job_typ_eec8a8_idx'), models.Index(fields=['correlation_id'], name='agents_agen_correla_4fb2b1_idx')],
            },
        ),
    ]
