# Generated by Django 5.0.14 on 2026-05-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0022_alter_agentjob_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentjob',
            name='job_type',
            field=models.CharField(choices=[('create_account', 'Create account'), ('provision_hosting', 'Provision hosting'), ('provision_openlitespeed_hosting', 'Provision OpenLiteSpeed hosting'), ('delete_account', 'Delete account'), ('suspend_account', 'Suspend account'), ('unsuspend_account', 'Unsuspend account'), ('create_domain', 'Create domain'), ('delete_domain', 'Delete domain'), ('create_php_pool', 'Create PHP-FPM pool'), ('create_database', 'Create database'), ('delete_database', 'Delete database'), ('change_database_password', 'Change database password'), ('collect_database_size', 'Collect database size'), ('create_dns_zone', 'Create DNS zone'), ('issue_ssl', 'Issue SSL certificate'), ('create_mail_domain', 'Create mail domain'), ('create_mailbox', 'Create mailbox'), ('change_mailbox_password', 'Change mailbox password'), ('suspend_mailbox', 'Suspend mailbox'), ('unsuspend_mailbox', 'Unsuspend mailbox'), ('delete_mailbox', 'Delete mailbox'), ('create_mail_alias', 'Create mail alias'), ('delete_mail_alias', 'Delete mail alias'), ('set_mailbox_quota', 'Set mailbox quota'), ('enable_dkim', 'Enable DKIM'), ('collect_mailbox_usage', 'Collect mailbox usage'), ('test_mail_delivery', 'Test mail delivery'), ('install_wordpress', 'Install WordPress'), ('wordpress_update', 'Update WordPress'), ('wordpress_delete', 'Delete WordPress'), ('deploy_python_app', 'Deploy Python app'), ('deploy_django_app', 'Deploy Django app'), ('deploy_node_app', 'Deploy NodeJS app'), ('deploy_laravel_app', 'Deploy Laravel app'), ('app_action', 'App action'), ('collect_app_logs', 'Collect app logs'), ('collect_account_usage', 'Collect account usage'), ('security_scan', 'Security scan'), ('create_ftp_user', 'Create FTP user'), ('create_sftp_user', 'Create SFTP user'), ('rotate_sftp_password', 'Rotate SFTP password'), ('file_list', 'List account files'), ('file_read', 'Read account file'), ('file_write', 'Write account file'), ('file_delete', 'Delete account file'), ('file_mkdir', 'Create account directory'), ('file_chmod', 'Change account file mode'), ('service_action', 'Service action')], max_length=80),
        ),
    ]
