# Generated by Django 5.0.14 on 2026-05-16 07:22

import secrets
from django.db import migrations, models


def populate_agent_secrets(apps, _schema_editor):
    node_model = apps.get_model("agents", "Node")
    for node in node_model.objects.filter(agent_secret=""):
        node.agent_secret = "agent_" + secrets.token_urlsafe(48)
        node.save(update_fields=["agent_secret"])


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0042_alter_agentjob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='agent_secret',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.RunPython(populate_agent_secrets, migrations.RunPython.noop),
    ]
